feat(ts): add `typeName` property to `TSTypeParameter`
babel/babel pull request #12829
Opened 2021-02-19 13:06 UTC by fedeci

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12825  
| Patch: Bug Fix?          |
| Major: Breaking Change?  | Not yet
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

We parse the entire identifier instead of just his name.
I chose to keep both `name` and `typeName` because otherwise `TSTypeParameter` interface would become a mess with optionals.

2021-02-19 13:11 UTC, fedeci commented on packages/babel-parser/src/types.js
> +  typeName: Identifier,
We can also handle this as a union type assigning it under the `BABEL_8_BREAKING` flag.
```suggestion
  name: string | Identifier,
```

2021-03-02 12:13 UTC, nicolo-ribaudo requested changes
Let's just do this for Babel 8 (`BABEL_8_BREAKING`).

This PR as-is is problematic because it introduces two different source of truth in the AST, and modifying `typeName` in a plugin doesn't have any effect on the generated code.

2021-03-08 19:21 UTC, fedeci commented
Those ~30 errors are all related to `babel-parser` fixtures that need to be updated. Is there a way to avoid duplicating them?

2021-03-08 19:33 UTC, fedeci commented on packages/babel-parser/src/types.js
>  export type TypeParameter = TypeParameterBase & {
`TypeParameter` also depends on `TypeParameterBase`, this must be changed too, right?

2021-03-09 08:47 UTC, nicolo-ribaudo commented
> Those ~30 errors are all related to babel-parser fixtures that need to be updated. Is there a way to avoid duplicating them?

You need to duplicate them, rename the copy as `...-babel-7`, and add `BABEL_8_BREAKING: true` and `BABEL_8_BREAKING: false` to the test options.

2021-03-09 10:44 UTC, fedeci commented
It's huge

2021-04-07 09:52 UTC, nicolo-ribaudo approved these changes

2021-06-28 21:56 UTC, nicolo-ribaudo approved these changes

2021-06-28 21:56 UTC, nicolo-ribaudo commented
I re-approved because I'm not sure about what changed since my last review, but I reviewed it again.

2021-06-29 02:47 UTC, existentialism approved these changes

2021-06-29 05:40 UTC, fedeci commented
Just wait to merge this that I have to update `TypeParameter` also.

2021-07-02 08:42 UTC, nicolo-ribaudo approved these changes

2021-07-02 08:44 UTC, nicolo-ribaudo commented
> Since Flow parses `TypeParameters.name` as a string we don't have to change that behaviour.

We might still decide that it's better to align our Flow implementation with our TS implementation, rather than aligning it with the Flow AST. However, that's a separate discussion and let's keep this PR only for TS.

2021-07-02 08:44 UTC, merged