Add `assertions` to `ExportNamedDeclaration` without `from`
babel/babel pull request #13957
Opened 2021-11-13 09:23 UTC by sosukesuzuki

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Add `assertions` to `ExportNamedDeclaration` without `from` when `importAssertions` is enabled.

According to [estree spec](https://github.com/estree/estree/blob/master/stage3/import-assertions.md#exportnameddeclaration):

> assertions must be an empty array when source is null.

2021-11-15 14:02 UTC, nicolo-ribaudo commented on packages/babel-parser/src/parser/statement.js
> +      }
I don't remember if our flow version supports it, but if it does we can do
```suggestion
      if (this.hasPlugin("importAssertions")) {
        node.assertions ??= [];
      }
```

2021-11-15 14:59 UTC, existentialism approved these changes

2021-11-15 15:34 UTC, nicolo-ribaudo commented
Ok, it looks like it doesn't support it :grimacing:

2021-11-15 16:02 UTC, JLHwung requested changes
We can assign assertions immediately after we have parsed them:

https://github.com/babel/babel/blob/966387d263896a22913c7e1a511f5cc96b345621/packages/babel-parser/src/parser/statement.js#L2019

2021-11-15 20:21 UTC, sosukesuzuki commented on packages/babel-parser/src/parser/statement.js
> -        node.source = null;
Actually, `node.source = null` is called in `maybeParseExportNamedSpecifiers` and `maybeParseExportDeclaration`. So we can remove this from here.

2021-11-15 20:54 UTC, JLHwung approved these changes

2021-11-16 10:53 UTC, nicolo-ribaudo approved these changes

2021-11-16 10:53 UTC, merged