Update shouldStoreRHSInTemporaryVariable.ts, use more deconstruction.
babel/babel pull request #14191
Opened 2022-01-21 05:06 UTC by zhangenming

use more deconstruction.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

2022-01-21 16:05 UTC, JLHwung commented on packages/babel-plugin-proposal-object-rest-spread/src/shouldStoreRHSInTemporaryVariable.ts
> +export default function shouldStoreRHSInTemporaryVariable(node: LVal) {
`LVal` is a type export. We'd better leave it as-is.

2022-01-21 16:05 UTC, JLHwung commented on packages/babel-plugin-proposal-object-rest-spread/src/shouldStoreRHSInTemporaryVariable.ts
> +        return shouldStoreRHSInTemporaryVariable(firstProperty.value as LVal);
ditto.

2022-02-01 15:10 UTC, JLHwung commented
@zhangenming Can you fix the lint warnings? You can fix them by running `make fix-js`.

2022-02-02 10:48 UTC, The-x-Theorist requested changes

2022-02-02 10:48 UTC, The-x-Theorist commented on packages/babel-plugin-proposal-object-rest-spread/src/shouldStoreRHSInTemporaryVariable.ts
> +const { isObjectProperty, isArrayPattern, isObjectPattern, isAssignmentPattern, isRestElement, isIdentifier } = t;
```suggestion
const {
    isObjectProperty,
    isArrayPattern,
    isObjectPattern,
    isAssignmentPattern,
    isRestElement,
    isIdentifier
} = t;
```

2022-02-02 10:48 UTC, The-x-Theorist commented on packages/babel-plugin-proposal-object-rest-spread/src/shouldStoreRHSInTemporaryVariable.ts
> +const { isObjectProperty, isArrayPattern, isObjectPattern, isAssignmentPattern, isRestElement, isIdentifier } = t;
Changing the deconstruction to this structure might solve the linting error in CI.

2022-02-13 14:47 UTC, nicolo-ribaudo approved these changes
Thanks!

2022-02-13 14:48 UTC, merged