Remove git.io shortlinks from repo [skip ci]
babel/babel pull request #14493
Opened 2022-04-26 05:21 UTC by Andoryuuta

Github has deprecated git.io and will be [disabling all links on April 29th](https://github.blog/changelog/2022-04-25-git-io-deprecation/).
This PR replaces all git.io shortened links with the URL they redirect to.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Removed soon-to-be-invalid shortlinks
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | No
| Documentation PR Link    | N/A
| Any Dependency Changes?  | No
| License                  | MIT

2022-04-26 12:26 UTC, JLHwung reviewed
Can you replace `master` to `main`?

2022-04-27 04:11 UTC, SukkaW requested changes

2022-04-27 04:11 UTC, SukkaW commented on packages/babel-core/src/parser/util/missing-plugin-helper.ts
> +      url: "https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-class-properties",
The URL returns 404.

2022-04-27 04:11 UTC, SukkaW commented on packages/babel-core/src/parser/util/missing-plugin-helper.ts
> +      url: "https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-class-properties",
The URL returns 404.

2022-04-27 04:11 UTC, SukkaW commented on packages/babel-core/src/parser/util/missing-plugin-helper.ts
> +      url: "https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-class-properties",
The URL returns 404.

2022-04-27 11:02 UTC, JLHwung approved these changes
The URLs returning 404 are archived plugins, we can fix them in another PR.

2022-04-27 22:20 UTC, nicolo-ribaudo approved these changes
Thanks! I agree, lets get this merged since it's quite urgent. We can iterate and improve the links later.

2022-04-27 22:29 UTC, merged