fix: Print multi-line inner comments of arrowFunc
babel/babel pull request #15159
Opened 2022-11-08 08:52 UTC by liuxingbaoyu

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-11-08 08:57 UTC, liuxingbaoyu commented on packages/babel-generator/src/generators/methods.ts
> +  this.print(node.returnType, node);
I'm not sure if this is going to be removed, although we no longer wrap comments here.

2022-11-27 06:43 UTC, nicolo-ribaudo approved these changes

2022-11-28 16:43 UTC, JLHwung requested changes
I feel like we should just remove this test case. 

In this case, the `innerComments` are not generated by the parser from a valid JS, instead it is manipulated by the AST transform.

The fact that
```js
(x, y) /* line break here
*/ => {}
```
is invalid implies that the transformed AST is invalid. Babel generator should not guarantee that it work with an invalid AST. In this case, I think it is fine to do nothing and just remove this test case. The generator may generate invalid JS if the AST is invalid.

2022-11-28 16:48 UTC, liuxingbaoyu commented
This test has nothing to do with this PR, this is a regression test, in https://github.com/babel/babel/pull/15160#issue-1440255815 we decided to never generate invalid code due to invalid comments.

2022-11-28 22:48 UTC, JLHwung commented
As is mentioned there, #15160 conflicts with this PR. The #15160 ensures that the generator prints valid code in `comments: false` and it somehow works with multi-line inner comments in arrow function.

It seems to me this PR "more specifically" supports multi-line inner comments in the [NLTH] position of the arrow function `() [No LineTerminator Here] => {}`. I am not convinced that we should do that, because 
1. The generator should spend the least efforts on in valid AST, as it is very likely a plugin issue. Moreover, a plugin can add inner comments to any AST nodes, e.g. `var x = 1` would not have inner comments at all. The current behaviour is to treat them as trailing comments of VariableDeclaration, which I think is fine. Of course we could print them around the `=` location, but doing so requires more efforts.
2. If we really want to change the behaviour, it should be applied to other `NLTH` as well, such as `async [NLTH] do`, `module [NLTH] {`, `yield [NLTH] AssignmentExpression`, etc.

2022-11-28 23:33 UTC, liuxingbaoyu commented
My personal preference is that we don't guarantee it but if someone wants to do it or if someone opens an issue about it we will accept it.
Because it's easy to implement without complicating the code.

Also this should restore the previous behavior where it was printed as inner comments a few PRs ago.

2023-12-23 03:02 UTC, closed without merging