chore: Commit corejs3 helpers
babel/babel pull request #16212
Opened 2024-01-12 04:32 UTC by liuxingbaoyu

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

It seems that there are many optimization possibilities for these outputs, and they are now committed as is to facilitate future reviews.

2024-01-12 04:46 UTC, liuxingbaoyu commented on .gitignore
> -/packages/babel-core/src/vendor/*.ts
packages/babel-core/src/vendor/import-meta-resolve.d.ts

2024-01-12 06:21 UTC, nicolo-ribaudo commented on eslint/babel-eslint-plugin/LICENSE
> -Copyright (c) 2014-2015 Jason Quense <jason@quense.me>
This license is different from the top-level one (different name), we should keeep it.

2024-01-22 18:23 UTC, nicolo-ribaudo approved these changes
I don't love this, but it's fine

2024-01-22 18:53 UTC, JLHwung requested changes
It seems to me the contents of corejs3 helpers are mostly babel helpers + corejs 3 imports. We already have babel-helpers in the repo, I see no compelling reason to include runtime-corejs3 helpers as well.

2024-01-22 19:15 UTC, liuxingbaoyu commented
I plan to open a series of PRs here and `babel-polyfills` to optimize the output.
If we don't commit them, it will be more difficult to review subsequent PRs.
For example
1. I hope to avoid unnecessary polyfills, such as `Array.push`, `forEach`, and I will check whether our usage is related to the fix of polyfills.
2. I wish to avoid simple polyfills of our own.
For example `X.y || function (){}. `

2024-01-22 19:39 UTC, liuxingbaoyu commented on packages/babel-runtime-corejs3/helpers/esm/applyDecs2305.js
> +import _pushInstanceProperty from "core-js-pure/features/instance/push.js";
I suspect these can be avoided or replaced with more precise polyfills, the automatically imported ones don't seem to be minimal.

2024-01-29 16:22 UTC, JLHwung reviewed
I am wondering if we can commit certain test snapshots, that only records the polyfill imports. So that 
1) we don't have to update corejs3 helpers in the git repo if there are any changes that does not introduce a new polyfill, and most changes I believe are of such kind
2) If we ever introduce `babel-runtime-es-shims`, we don't have to commit a bunch of helpers again
3) If we introduce new polyfills in the helper, the changes will be more convenient to review: the helper changes in `babel-helpers` and the polyfill import changes in the runtime-corejs3 snapshots

2024-01-30 15:17 UTC, liuxingbaoyu commented
This is possible, but may not be convenient.
Because reviewers still need to check the output file locally to make sure the `import` changes are expected.

> * If we ever introduce `babel-runtime-es-shims`, we don't have to commit a bunch of helpers again

This is only necessary if we want to try further optimizations, for example `core-js-2` was not submitted.

2024-01-31 17:18 UTC, JLHwung approved these changes

2024-03-05 17:55 UTC, nicolo-ribaudo commented
@liuxingbaoyu Could you rebase and then merge?

2024-03-05 21:30 UTC, JLHwung approved these changes

2024-03-06 07:42 UTC, merged